language: r

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

r:
  - devel
  - release

sudo: false

cache: packages

r_check_args: --as-cran

r_github_packages:
  - leifeld/xergm.common
  - statnet/ergm
  - jaredhuling/fastglm

r_packages:
  - covr
  
notifications:
  email:
    recipients:
      - philip.leifeld@essex.ac.uk
    on_success: change
    on_failure: change

after_success:
- Rscript -e 'library(covr); codecov()'
